import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=new URL('../',import.meta.url);const m=JSON.parse(await fs.readFile(new URL('data/model.json',root),'utf8'));const wb=Workbook.create();
await fs.mkdir(new URL('work/',root),{recursive:true});
const names={segments:'Segments',strategies:'Strategies',scenarios:'Scenarios',years:'Years',assumptions:'Assumptions',respondents:'Respondents',responses:'Responses'};
const col=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
const sh={};for(const n of ['Decision',...Object.values(names),'Segment analysis','Forecast','Price test','Notes'])sh[n]=wb.worksheets.add(n);
function table(name,headers,rows){let s=sh[name];s.getRangeByIndexes(0,0,1,headers.length).values=[headers];if(rows.length)s.getRangeByIndexes(1,0,rows.length,headers.length).values=rows;s.showGridLines=false;s.getRangeByIndexes(0,0,rows.length+1,headers.length).format.font={name:'Arial',size:10,color:'#172B3A'};s.getRangeByIndexes(0,0,1,headers.length).format={fill:'#243746',font:{name:'Arial',bold:true,color:'#FFFFFF'},wrapText:true,rowHeight:42};s.getRangeByIndexes(0,0,rows.length+1,headers.length).format.columnWidth=19;s.getRangeByIndexes(1,0,Math.max(rows.length,1),headers.length).setNumberFormat('#,##0.00;[Red](#,##0.00);â€“');s.freezePanes.freezeRows(1);return s;}
for(const [k,rows]of Object.entries(m.raw)){table(names[k],Object.keys(rows[0]),rows.map(Object.values));sh[names[k]].getRangeByIndexes(1,0,rows.length,Object.keys(rows[0]).length).format.font.color='#215EA8';}
sh.Strategies.getRange('B:B').format.columnWidth=29;sh.Segments.getRange('B:B').format.columnWidth=29;sh.Respondents.getRange('E:E').format.columnWidth=23;
for(const [s,r]of [['Strategies','J2:K6'],['Scenarios','C2:E4'],['Assumptions','B2:C2'],['Assumptions','F2:H2']])sh[s].getRange(r).setNumberFormat('0.0%');
sh.Responses.getRange('D1:E1').values=[['Qualified','Segment ID']];sh.Responses.getRange('D1:E1').format={fill:'#243746',font:{color:'#FFFFFF',bold:true},columnWidth:19};
for(let i=2;i<=601;i++){sh.Responses.getRange(`D${i}:E${i}`).formulas=[[`=IF(AND(C${i}=1,INDEX('Respondents'!$C$2:$C$121,MATCH(A${i},'Respondents'!$A$2:$A$121,0))>=INDEX('Strategies'!$C$2:$C$6,MATCH(B${i},'Strategies'!$A$2:$A$6,0))),1,0)`,`=INDEX('Respondents'!$B$2:$B$121,MATCH(A${i},'Respondents'!$A$2:$A$121,0))`]];}
table('Segment analysis',Object.keys(m.segment_analysis[0]),m.segment_analysis.map(Object.values));
for(let i=2;i<=21;i++){
 const st=m.segment_analysis[i-2].strategy_id+1,se=m.segment_analysis[i-2].segment_id+1;
 sh['Segment analysis'].getRange(`C${i}:I${i}`).formulas=[[`=COUNTIF('Respondents'!$B$2:$B$121,B${i})`,`=SUMIFS('Responses'!$C$2:$C$601,'Responses'!$B$2:$B$601,A${i},'Responses'!$E$2:$E$601,B${i})`,`=SUMIFS('Responses'!$D$2:$D$601,'Responses'!$B$2:$B$601,A${i},'Responses'!$E$2:$E$601,B${i})`,`=E${i}/C${i}`,`=SUMIF('Respondents'!$B$2:$B$121,B${i},'Respondents'!$C$2:$C$121)/C${i}`,`='Segments'!C${se}`,`=H${i}*F${i}*'Assumptions'!$C$2*'Strategies'!L${st}`]];
}sh['Segment analysis'].getRange('F2:F21').setNumberFormat('0.0%');
table('Forecast',Object.keys(m.forecast[0]),m.forecast.map(Object.values));
for(let i=2;i<=46;i++){let r=m.forecast[i-2],st=r.strategy_id+1,sc=r.scenario_id+1,y=r.period+1;
 sh.Forecast.getRange(`E${i}:O${i}`).formulas=[[
 `=ROUND(SUMIF('Segment analysis'!$A$2:$A$21,A${i},'Segment analysis'!$I$2:$I$21)*'Scenarios'!C${sc}*'Years'!C${y},0)`,
 `=E${i}*'Strategies'!C${st}*'Strategies'!D${st}`,`=E${i}*SUM('Strategies'!E${st}:G${st})*'Scenarios'!D${sc}`,`='Strategies'!I${st}`,`=E${i}*'Strategies'!J${st}*'Scenarios'!E${sc}`,`=I${i}*'Assumptions'!$E$2*'Assumptions'!$F$2`,`=('Assumptions'!$D$2-I${i})*'Assumptions'!$E$2*'Assumptions'!$F$2*O${i}`,`=F${i}-G${i}-H${i}-J${i}-K${i}`,`=L${i}/(1+'Assumptions'!$B$2)^D${i}`,`=I${i}/'Assumptions'!$D$2`,`='Strategies'!K${st}*'Scenarios'!E${sc}`]];
}sh.Forecast.getRange('N2:O46').setNumberFormat('0.0%');
table('Decision',['Strategy','Scenario','3-year NPV USD','Units','Revenue USD','Mechanical loss USD','Brand loss USD','Max displacement','Brand haircut','NPV > 0','Risk within limits'],m.summary.map(r=>[m.raw.strategies[r.strategy_id-1].strategy,m.raw.scenarios[r.scenario_id-1].scenario,...Object.values(r).slice(2),null,null]));
for(let i=2;i<=16;i++){let r=m.summary[i-2],st=r.strategy_id+1,rows=m.forecast.map((v,j)=>v.strategy_id===r.strategy_id&&v.scenario_id===r.scenario_id?j+2:null).filter(Boolean),lo=rows[0],hi=rows[2];sh.Decision.getRange(`C${i}:K${i}`).formulas=[[`=SUM('Forecast'!M${lo}:M${hi})-'Strategies'!H${st}`,`=SUM('Forecast'!E${lo}:E${hi})`,`=SUM('Forecast'!F${lo}:F${hi})`,`=SUM('Forecast'!J${lo}:J${hi})`,`=SUM('Forecast'!K${lo}:K${hi})`,`=MAX('Forecast'!N${lo}:N${hi})`,`=MAX('Forecast'!O${lo}:O${hi})`,`=C${i}>0`,`=AND(H${i}<='Assumptions'!$G$2,I${i}<='Assumptions'!$H$2)`]];}
sh.Decision.getRange('A:A').format.columnWidth=29;sh.Decision.getRange('H2:I16').setNumberFormat('0.0%');sh.Decision.getRange('C2:C16').conditionalFormats.add('cellIs',{operator:'lessThan',formula:0,format:{font:{color:'#A33030'}}});
sh.Decision.getRange('A19:F22').values=[['Decision: defer commercial entry',null,null,null,null,null],['No entry: incremental NPV = $0',null,null,null,null,null],['All data and scenario outputs are synthetic.',null,null,null,null,null],['Power BI is the main dashboard; see build guide.',null,null,null,null,null]];
table('Price test',['Price USD','Qualified n','Annual units','Contribution / unit','3-year NPV USD','Year 1 units','Year 2 units','Year 3 units','Year 1 cash','Year 2 cash','Year 3 cash'],m.pricing.map(r=>[...Object.values(r),null,null,null,null,null,null]));
// Price qualification is recalculated from respondent WTP and sibling-concept interest.
sh.Respondents.getRange('F1').values=[['Sibling interest']];for(let i=2;i<=121;i++)sh.Respondents.getRange(`F${i}`).formulas=[[`=SUMIFS('Responses'!$C$2:$C$601,'Responses'!$A$2:$A$601,A${i},'Responses'!$B$2:$B$601,'Strategies'!$A$3)`]];
for(let i=2;i<=5;i++){
sh['Price test'].getRange(`B${i}:E${i}`).formulas=[[`=COUNTIFS('Respondents'!$C$2:$C$121,">="&A${i},'Respondents'!$F$2:$F$121,1)`,`=(${m.raw.segments.map((s,j)=>`'Segments'!C${j+2}*COUNTIFS('Respondents'!$B$2:$B$121,'Segments'!A${j+2},'Respondents'!$C$2:$C$121,">="&A${i},'Respondents'!$F$2:$F$121,1)/COUNTIF('Respondents'!$B$2:$B$121,'Segments'!A${j+2})`).join('+')})*'Assumptions'!$C$2*'Strategies'!$L$3`,`=A${i}*'Strategies'!$D$3-SUM('Strategies'!$E$3:$G$3)`,`=I${i}/(1+'Assumptions'!$B$2)^'Years'!$B$2+J${i}/(1+'Assumptions'!$B$2)^'Years'!$B$3+K${i}/(1+'Assumptions'!$B$2)^'Years'!$B$4-'Strategies'!$H$3`]];
for(let j=0;j<3;j++){let u=col(5+j),cash=col(8+j);sh['Price test'].getRange(`${u}${i}`).formulas=[[`=ROUND(C${i}*'Years'!C${j+2},0)`]];sh['Price test'].getRange(`${cash}${i}`).formulas=[[`=${u}${i}*(D${i}-'Strategies'!$J$3*'Assumptions'!$E$2*'Assumptions'!$F$2*(1-'Strategies'!$K$3))-'Strategies'!$I$3-'Assumptions'!$D$2*'Assumptions'!$E$2*'Assumptions'!$F$2*'Strategies'!$K$3`]];}}
table('Notes',['Topic','Explanation'],[['Scope','Fictional Maison Valenne. Synthetic US scenario, 2027â€“2029; USD.'],['Inputs','Blue text identifies editable synthetic raw inputs. Calculations use dark text.'],['Workflow','Raw CSVs â†’ MySQL views â†’ formula Excel cross-check â†’ Power BI CSV model.'],['Recalculation','Excel formulas recalculate after edits. Regenerate CSV/SQL/Power BI separately; no live cross-tool sync.'],['Decision','All entry NPVs negative; no entry benchmark is zero. See strategy memo for limits.'],['Cash definition','Pre-tax operating-cash proxy; excludes financing, working capital and terminal value.'],['Brand risk','Haircut applies to residual mechanical contribution after displaced units.'],['Sample','120 synthetic people, 30 per segment; 600 concept ratings. Stated preference, not causal evidence.'],['Demand','Qualified share Ã— annual reachable audience Ã— 12% calibration Ã— demand factor Ã— ramp.'],['Forecast rows','Strategy Ã— scenario Ã— year. Alternative strategies and scenarios must not be summed.'],['Sources','All raw numeric model assumptions are synthetic. Public reference prices do not calibrate forecasts.'],...m.sources.map(s=>[s.item,s.source_url]),['Source date','Public references accessed 2026-09-19; Apple price is its 2025 launch price.'],['Power BI','Manual Action Required: build/save PBIX and execute DAX acceptance checks.']]);sh.Notes.getRange('A:A').format.columnWidth=30;sh.Notes.getRange('B:B').format.columnWidth=105;sh.Notes.getRange('B2:B17').format.wrapText=true;sh.Notes.getRange('A2:B17').format.rowHeight=42;
sh.Respondents.getRange('F1:F121').format.columnWidth=21;sh.Respondents.getRange('F1').format={fill:'#243746',font:{name:'Arial',bold:true,color:'#FFFFFF'},wrapText:true,rowHeight:42};
for(const name of Object.keys(sh)){let h=sh[name].getUsedRange().values[0];sh[name].getRangeByIndexes(0,0,1,h.length).values=[h.map(x=>typeof x==='string'?x.replaceAll('_',' '):x)];}
for(const [name,ranges]of Object.entries({Strategies:['A2:A6'],Segments:['A2:A5','C2:D5'],Scenarios:['A2:A4'],Years:['A2:B4'],Assumptions:['A2:A2','D2:E2'],Respondents:['A2:D121','F2:F121'],Responses:['A2:E601'],'Segment analysis':['A2:E21','H2:H21'],Forecast:['A2:E46'],Decision:['D2:D16'],'Price test':['A2:C5','F2:H5']}))for(const r of ranges)sh[name].getRange(r).setNumberFormat('#,##0');
sh.Strategies.getRange('D2:D6').setNumberFormat('0.0%');sh.Segments.getRange('E2:E5').setNumberFormat('0.0%');
const errors=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:50},summary:'Final error scan'});await fs.writeFile(new URL('validation/excel_error_scan.json',root),errors.ndjson);
let checks=[];for(let i=0;i<m.summary.length;i++){let value=sh.Decision.getRange(`C${i+2}`).values[0][0];if(typeof value!=='number'||Math.abs(value-m.summary[i].npv)>.02)throw Error(`NPV mismatch ${i}: ${value} vs ${m.summary[i].npv}`);checks.push({row:i+2,excel_npv:value,reference_npv:m.summary[i].npv,error:Math.abs(value-m.summary[i].npv)});}
for(let i=0;i<4;i++){let value=sh['Price test'].getRange(`E${i+2}`).values[0][0];if(Math.abs(value-m.pricing[i].npv)>.02)throw Error('Price mismatch '+value);}
await fs.writeFile(new URL('validation/excel_reconciliation.json',root),JSON.stringify(checks,null,2));
for(const [name,rows]of [['Forecast',m.forecast],['Segment analysis',m.segment_analysis]])for(let i=0;i<rows.length;i++){const vals=sh[name].getRangeByIndexes(i+1,0,1,Object.keys(rows[i]).length).values[0];Object.values(rows[i]).forEach((v,j)=>{if(typeof vals[j]!=='number'||Math.abs(vals[j]-v)>.02)throw Error(`${name} mismatch ${i} ${j}: ${vals[j]} vs ${v}`);});}
for(const name of Object.keys(sh)){let range=name==='Notes'?'A1:B9':name==='Decision'?'A1:F9':name==='Forecast'?'E1:M7':name==='Responses'?'A1:E9':name==='Respondents'?'A1:F9':name==='Segment analysis'?'A1:I7':name==='Price test'?'A1:E5':`A1:${col(Math.min(Object.values(m.raw).find(r=>names[Object.keys(m.raw).find(k=>m.raw[k]===r)]===name)?.[0]?Object.keys(Object.values(m.raw).find(r=>names[Object.keys(m.raw).find(k=>m.raw[k]===r)]===name)[0]).length-1:7,7))}7`;
let img=await wb.render({sheetName:name,range,scale:1.3,format:'png'});await fs.writeFile(new URL(`work/preview-${name.replaceAll(' ','-')}.png`,root),new Uint8Array(await img.arrayBuffer()));}
await (await SpreadsheetFile.exportXlsx(wb)).save(new URL('excel/Case3_Analysis.xlsx',root).pathname.replace(/^\/(.:)/,'$1'));
console.log('Workbook exported and 15 NPV / 4 pricing results reconciled.');
